### ISSUE TITLE
description: 'Unexpected token -

### ISSUE THREAD

**Issue by debbas** [ipselon/react-ui-builder#43]
Hi I'm getting unexpected token when I add style

Error 
{ [Error: Line 60: Unexpected token -]
  index: 1560,
  lineNumber: 60,
  column: 134,
  description: 'Unexpected token -' }

File index.js https://gist.github.com/debbas/5f2332ca1795913319fd

Please let me know what is wrong.

**Comment by ipselon** [comment]
Change background-color to backgroundColor

**Comment by ipselon** [comment]
@debbas Could you please republish your project on the gallery, it seems has some errors.

**Comment by debbas** [comment]
@ipselon  Done :)

**Comment by ipselon** [comment]
@debbas Thanks !

**Comment by debbas** [comment]
@ipselon  

Here is my suggestion after using it for couple of hours. First of all its awesome, I been thinking on implementing something to host all UI components that people can reuse for rapid development.

You should have a new screen for Developers who want to create new components by writing code.
Plus if you want a complete component you should be able to add style, JS for the functionality. 

For example let's say I want to have a Chat app
I would like to split that to multiple components:
1- List of Online Users (Takes Data json of users)
2- ListItem for each User with their Info (Load User Info from passed data from 1)
3- Message View that will be a container of all messages list and a composer
4- List of all Messages (Takes Data json of history messages)
5- ListItem of each Message(Load message info from passed data from 4)
6- Composer that allow users to input their text and send. 

I found a way to create components but wasn't easy to use.

**Comment by ipselon** [comment]
Thanks. 

First of all the builder was created for developers to help them to do fast prototyping of UI. Of cause, there are features which help to combine and reuse components, event to generate the source code for new component, but in terms of development process this is not enough for creating really enhanced components. As you mentioned, developer has to have a field where he can develop the source code of components, actions, stores, etc., and there are plenty of IDE and advanced text editors for this, and the builder is the only nice addition to development process, which removes a lot of boring routines, and gives visual help and guiding in UI composition.

So, I think that adding a source code editor into the builder is redundant and not worth the time which it would take. 

But what is more interesting that is working with state in Rect, kinda redux. Actually, the next version of the builder will use all nice features of redux library, with hot loading and integrated Redux DevTools, plus React Router. With new builder you will not have to install and setup all react/redux environment, just start development of an application.

As for creating complex components in builder, you have to remember that after you combine your UI, and in order to have nicely decoupled components start generate the source code from the most low level component in your hierarchy.
